language: java
jdk:
- openjdk8
# git strips the wrapper jar file so we have to force its download during the build
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
deploy:
  provider: heroku
  api_key:
    secure: "EoBrhDeApiQMjzU/i8Qu9DQI0HWmUbd6Q/ozutvPAqKcuRkmt5GpVvJZ+TqROnUBtnhJnd9tegYO0FDxN1E39KYQxZ8VF+llIoZVS9I4SX47EMoXLq869Fut59vh2Pnd3uRmZ48HUDRpwObQqAZDK/QoVppp9bzfCeyjFziApBYq5U2pZQefZ8Sd1305Mnfpm/ZWWXeaAjPwiYDaNr0olJ6PKbdNHDqwar+to5Sg4FVTfQAIgTfQozWGJS5Zk7rVWFLQIScdEXpVb+vTp1js22RoXrzvRaEoPF/OjNRCYXPWlAXv0ugsbqM5AD21ybU5h3EIJ/cmvQBN/cbyrBuU9tZOZ0/buSyaAYCY0lTJVz4q0k5nPARKIYdAbbrsr4GK3zaMXgZznEUd65VEedKyiPql1G4cZpg3RL80evVYwpVgJiPj7S9hrsr6SqvSeYoY1J/eED1Qj+WGSOOB8tIVLsMPniQ3ckvvHJDXWYs6/O6dCmf6VaDCXuy+D1ih6gbYQEpsDyw8Tq3yzXk7kAnfNgr1xrkgNdYw3GmxVF131/QUwdiW2lO5OseWlZIocaCN1qHAlW+NmJF+EJMi7fWVSEbGHtZX9N6q5EvzmM8C7FssP4/21ajVkfAzF+/JPPf8fnlJDhl7OyKkwkY2kpsNZS4eK1gi0jaLYIVKdOg9gLM="
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report